### PR TITLE
max_space option (issue 2)

### PR DESCRIPTION
**Pull request by simmstein**
Add the max_space option

### CODE REVIEW

**Comment by jvaubourg** [comment]
Thank you for your contribution!

But, I think there is a problem with your solution:

```
df $base_path | tail -n 1 | awk '{print $5}' | sed 's/%//'
```

The _base_path_ option corresponds to the root of the files for the webserver (e.g. _/var/www/piratebox/_). It not corresponds to any mount point and will not appear in the _df_ list.

I thinks using _df_ is not a good solution, because this requires une dedicated partition for the piratebox setup. And if the user has a dedicated partition, he does not need an option for limiting the max space.

**Comment by simmstein** [comment]
If you give a random directory path to df, it will determine the associated mount point and return you the information you need.

``` bash
$ df | grep secured
/dev/mapper/secured   164245908  58834748   97044824  38% /secured
$ df /secured/var
Sys. de fichiers    blocs de 1K  Utilisé Disponible Uti% Monté sur
/dev/mapper/secured   164245908 58834748   97044824  38% /secured
```

**Comment by jvaubourg** [comment]
Oh, okay, I didn't known that :).

But e.g. if the user has only one partition ("/") on its machine, the percentage corresponds to the space used by the whole system and not the space used by its piratebox. This feature is useful anyway but that is would not be better to use a PHP function to determine the size of the uploads/ folder?

**Comment by simmstein** [comment]
It depends what you want to do:
- set a maximum size to the upload directory
- reduce sys admin problem with a disk 100% used
  I prefer the second solution because you don't want to overload your system.

Btw, we can have the 2 options :)

**Comment by jvaubourg** [comment]
You're right, I like this explanation. Even though I'm not sure creating new process (shell, df, tail, awk and sed) is really more efficient than computering a folder size with PHP.

**Comment by jvaubourg** [comment]
Your contribution was integrated to the corresponding YunoHost app: https://raw.githubusercontent.com/labriqueinternet/piratebox_ynh/master/screenshot_admin.png

**Pull request merged**
